Dual-Life/Devel-PPPort

Changes
HACKERS
Makefile.PL
PPPort_pm.PL
PPPort_xs.PL
parts/apidoc.fnc
parts/inc/HvNAME
parts/inc/gv
parts/todo/5013007
parts/todo/5015004

Add HvNAMELEN, HvNAMEUTF8, HvENAME, HvENAMELEN, HvENAMEUTF8
gv_fetchpvn, gv_fetchmethod_flags, gv_init_pv, gv_init_pvn, gv_init_sv
Tested ok on all major perl versions down to 5.6.2

Add parts for binary names

---

parts/inc/misc

This was happening when compiling DBD::mysqlx 0.003 with DBI 1.642
Note that dbipport.h is a ppport.h
In file included from /usr/lib64/perl5/vendor_perl/auto/DBI/DBIXS.h:38,
from dbdimp.h:11,
from mysqlx.h:7,
from mysqlx.xs:10:
/usr/lib64/perl5/vendor_perl/auto/DBI/dbipport.h:4471: warning: "WIDEST_UTYPE" redefined
In file included from /usr/lib64/perl5/CORE/perl.h:2465,
from /usr/lib64/perl5/vendor_perl/auto/DBI/DBIXS.h:23,
from dbdimp.h:11,
from mysqlx.h:7,
from mysqlx.xs:10:
/usr/lib64/perl5/CORE/handy.h:1064: note: this is the location of the previous definition

Don't redefine WIDEST_UTYPE

---

Makefile.PL

Add a warning about `"Warning: Please check '__MAX_PERL__' value in PPPort_pm.PL` when running make 'dist'

Add a warning when generating make dist

---

parts/inc/misc

The leaky code is only used during test. It creates 3 ops, does various
operations related to linking OpSIBLINGs, then fails to free them.

fix leak in Devel-PPPort

---

parts/inc/uv

The xs code that interfaces between the .t and the C code was not
properly dealing with the size differences.  I copied the similar code
from perl core XS-APItest, and that works

Fix tests for 64bit int, 32bit ptr platforms

---

parts/inc/uv

Wrong for some failure conditions, anyway.  It should get fixed early in
5.31, make the cutoff here 5.31.2 to give us some leeway, so don't have
to change Devel::PPPort again.

5.30 utf8_to_uvchr_buf still has wrong retval

---

Makefile.PL

Fixes GH #68
make sure we regenerate the manifest
when building a dist.
We recently removed on purpose the
MANIFEST file from the git repo to
make sure we always generate a fresh
version on dist...

dist target now depends on manifest

---

parts/apicheck.pl
parts/inc/SvPV
parts/inc/misc
parts/inc/newRV
parts/inc/newSV_type
parts/inc/newSVpv
parts/inc/ppphtest
parts/inc/sv_xpvf
t/ppphtest.t

So their usage via ppport.h can be done via specifying corresponding NEED_.

Define more API functions as macros

---

parts/inc/uv
parts/todo/5015009
t/uv.t

API defines first argument of utf8_to_uvchr_buf() as const. So users of
this API expects that they can pass const variable. Fix it by explicit
casting of non-const var to const in D_PPP_utf8_to_uvchr_buf_callee() call.
Change also tests to verify that const argument can be really passed.
Remove utf8_to_uvchr_buf() from TODO list as it is now implemented.
Do not compile test functions which are not provided for older Perl
versions.

Fix utf8_to_uvchr_buf()

---

devel/mkapidoc.sh
parts/inc/uv

Without this, it doesn't compile for me, but I don't know why it seems to in other environments

parts/inc/uv: A char* should be a U8*

---

devel/mkapidoc.sh
parts/apidoc.fnc
parts/ppptools.pl

Instead of expecting whoever is updating the embed.fnc to remember that
this extra line is required, do it while parsing it.  This means that
the embed.fnc can just be copied from the latest blead.

mkapidoc.sh: Add required line to generated apidoc.fnc

---

parts/ppptools.pl

The latest doc entries have a flag indicating that special handling is
used.  Use this flag here instead of knowing the specific current cases
that required it.

ppptools.pl: Remove special case

---

parts/inc/call
parts/inc/mess
parts/inc/misc
t/mess.t

ERRSV macro is function call, so ensure that it is not called more times.
Therefore pass it only to macros which evaluate its arguments only once.
Backported croak_sv() macro is changed to evaluate its argument only once,
like implementation in core Perl.

Fix processing ERRSV and croak_sv

---

parts/inc/uv

Fix unused variable warning in 5.30

---

.travis.yml

Unfortunately, dmake-based Strawberry Perl (prior 5.26) does not work.

Test Strawberry Perl on Travis Windows Build Environment

---

parts/inc/uv

I failed to push the fix to blead in time for 5.31.2, so continue to use
the fixed version in ppport.  I will shortly fix blead.

Use ppport's utf8_to_uvchr_buf through 5.31.3

---

.travis.yml
mktests.PL

MSWin32 use backslashes, so change them to slashes.
Fixes #106

Fix mktests.PL to produce same output on Linux and Windows

---

parts/inc/utf8

These are more correct synonyms for is_ascii_string

Backport is_utf8_invariant_string, is_invariant_string

---

parts/inc/call
t/call.t

Seems that check for SvROK() and SvTRUE() is enough, see:
https://rt.perl.org/Public/Bug/Display.html?id=134177
https://rt.perl.org/Public/Bug/Display.html?id=134175

Fix eval_pv for Perl versions prior to 5.31.2

---

parts/inc/magic
parts/todo/5013002
parts/todo/5013006
t/magic.t

Use sv_mortalcopy_flags() macro with SV_NOSTEAL flag to create non-magical
copy of input scalar. And on this non-magical copy call original Perl's
SvIV/SvUV/SvNV/SvTRUE macro.
This would ensure that get magic is not processed on original input scalar
argument and also that correct value is returned.

Implement SvIV_nomg(), SvUV_nomg(), SvNV_nomg() and SvTRUE_nomg()

---

mktests.PL
parts/inc/utf8
t/utf8.t

Also fix sv_len_utf8() for Perl versions prior to 5.17.5.

Implement sv_len_utf8_nomg() and sv_len_utf8()

---

parts/inc/Sv_set

Fixes #140
This is a patch from @pali, to fix the
failure seen by @skaji on p5-Text-Xslate.

Fix p5-Text-Xslate on Perl 5.8.5

---

parts/inc/utf8

```
Creating library blib\arch\auto\Devel\PPPort\PPPort.lib and object blib\arch\auto\Devel\PPPort\PPPort.exp
RealPPPort.obj : error LNK2001: unresolved external symbol MIN
blib\arch\auto\Devel\PPPort\PPPort.dll : fatal error LNK1120: 1 unresolved externals
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\bin\HostX64\x64\link.EXE"' : return code '0x460'
Stop.
```

Fix compilation with Visual C++

---

parts/inc/mess
t/mess.t

This seems to happen only when Devel::PPPort was built with
Visual C++ and nmake as a standalone distribution.
perl/perl5@1ddd2f5fcd8802a45ffd773aec3af107f37613f6 had fixed that
before, but the change was made only in the autogenerated test file
and it was discarded when the tests were regenerated.

fix mess.t failures when $0 contains backslashes

---

parts/inc/SvPV

If sv_2pv_flags() is called without SV_GMAGIC flag then temporary turn off
SVs_GMG flag (via SvGMAGICAL_off) on passed scalar, call standard sv_2pv()
and restore SVs_GMG flag (via SvGMAGICAL_on). Same for sv_pvn_force_flags().

Implement SV_GMAGIC flag for sv_2pv_flags() and sv_pvn_force_flags() for Perl versions < 5.7.2

---

t/testutil.pl

As fallback use 'C*' pack format which should be supported also on old Perl versions.
Fixes Perl 5.5.3 error: Invalid type in unpack: 'U' at Devel-PPPort/t/testutil.pl

Do not use 'U*' pack format on Perl versions which do not support it

---

parts/inc/ppphbin

Module warnings.pm is not available for these old versions.

Fix t/ppphtest.t for Perl versions prior to 5.6.0

---

parts/inc/call

Fixes error: symbol lookup error: blib/arch/auto/Devel/PPPort/PPPort.so: undefined symbol: Perl_eval_sv

Fix eval_sv for Perl versions prior to 5.6.0

---

t/testutil.pl

Tests should not throw warnings, so make them fatal.

Report fatal die error when test throw warning

---

.github/workflows/linux.yml
.github/workflows/macos.yml
.github/workflows/windows.yml

Add some basic GitHub actions
so we can smoke on GitHub containers
on linux, macos and windows.
For now only linux smoke multiple flavors of Perl.

Basic GitHub Actions

---

parts/inc/misc

In some platforms and configurations, it was getting 'signed'
Diagnosed by pali++

D:P: Make sure WIDEST_UTYPE is unsigned

---

.gitignore
Makefile.PL
devel/update_release_date.pl
parts/inc/version

When running make regen_release_date which
is trigger as part of make regen or make dist
we are updating parts/inc/version with the
current timestamp for the day.
This commits setup the build timestamp but nothing
is consuming it yet at this point.

Setup D_PPP_RELEASE_DATE on dist

---

Makefile.PL

And in MMS or MMK on VMS it's a syntax error.  So only spell it
with a dot when not using those utilities to run Devel::PPPort's
Makefile.PL.
(cherry picked from commit b6efc7071950ca9585eb17fc358efaee5df1ff14)
Signed-off-by: Nicolas R <atoomic@cpan.org>

.PHONY is specific to Unix make utilities.

---

parts/inc/cop
parts/inc/misc

These were removed from Perl in
https://github.com/perl/perl5/commit/eb578fdb5569b91c28466a4d1939e381ff6ceaf4,
let's remove them from here as well.

Remove C `register` declarations

---

parts/inc/mess

This is matching what's done in ExtUtils::ParseXS::Utilities
and avoids to redefine croak_xs_usage later.
References: #194

Define PERL_ARGS_ASSERT_CROAK_XS_USAGE when setting croak_xs_usage

---

devel/scanprov

Commit 622fbe37e275776fe46e650d84b84a946bc46931 rearranged this loop,
but forgot to remove the use of the `$new_code` variable.

Fix scanprov

---

parts/inc/locale

This reverts commit 7f61b87a443bb1a3daa87817c3ceeec2630d5a56.
This commit was inadvertently pushed; it isn't ready yet.

Revert "Backport Perl_setlocale"

---

parts/inc/utf8

strlen might be NULL - the code needs to check this before attempting to assign to it. This case is hit by one of Data::Dumper's regression tests.

The utf8_to_uvchr_buf implementation misses a NULL check in one place.

---

Makefile.PL

Add the flag for gcc for perl v5.35.4 and earlier.

Devel::PPPort shouldn't unconditionally -Wdeclaration-after-statement

---

parts/inc/misc

This fixes up 6d66b125bb339b62c0d8d4283d3fe576795764ce so that the
Devel::PPPort portion works on all supported Perls.
Basically, we have to preserve the pre-existing behavior for all Perls
that still have VOIDFLAGS, which was removed by:
Author: Nicholas Clark nick@ccl4.org
Date: Wed Sep 11 11:54:42 2013 +0200
Eliminate the only use of VOIDFLAGS, as part of STMT_START in perl.h
STMT_START has used VOIDFLAGS as part of its conditional compilation
since it was added by commit 728e280 (March 1996). The code originally
read:
/* Now which other defined()s do we need here ??? */
Since then it has been amended to avoid entering that definition for GCC
on Solaris. Given that all current Solaris compilers are C89 conformant,
VOIDFLAGS will always be true (actually 15), so the test is redundant. …

Devel::PPPort: Fix STMT_START { ... } STMT_END

---

parts/base/5035010
parts/embed.fnc
parts/inc/utf8
parts/todo/5035010

Closes #219
5.35.9 introduced a bug when called with an empty string.  It has been illegal to do this for some releases now, but it was legal for most of the lifespan of UTF-8, and D-PPPort has tested for it.  So on non-debugging builds, Perl behaves as it used to, returning that the input is malformed, and potentially raising an error.  But this is broken in blead at the moment.
In working on this problem, I found two instances in blead where it derefernces a string which is supposedly empty.  This bug dates at least to 5.31.4.
So these patches workaround two bugs in core Perl.

Fix utf8_to_uvchr_buf issue with Perl >= 5.35.9

---

Changes
parts/inc/misc

Perl v5.27.7 switched dNOOP to use an incomplete struct
declaration, regardless of the language.
This change is also going to update dNOOP on older versions.
Upstream-URL: https://github.com/Perl/perl5/commit/91ca80c3dda3ce14add7bd63f815556667be2fd4

parts/inc/misc: backport dNOOP change

---

Makefile.PL

GitHub no longer supports the git:// protocol since it is unencrypted.

change github clone URL from git:// to https://

---

parts/inc/SvPV

Fixes: https://github.com/Dual-Life/Devel-PPPort/issues/231

Fix sv_2pv and sv_2pv_flags for Perl < 5.17.2

---

parts/inc/SvPV

Apply several fixes after review while submitting
changes from this repo to blead.
Upstream-URL: https://github.com/Perl/perl5/pull/21453

Adjust SvPV after review

---

parts/inc/SvPV

also prefer using PERL_USE_GCC_BRACE_GROUPS.

Stop using PL_na for sv_2pv_flags and sv_2pv_flags

---

t/testutil.pl

The fix follows Zefram's suggestion from
https://www.nntp.perl.org/group/perl.perl5.porters/2012/05/msg186846.html
> On older perls, however, $] had a numeric value that was built up using
> floating-point arithmetic, such as 5+0.006+0.000002.  This would not
> necessarily match the conversion of the complete value from string form
> [perl #72210].  You can work around that by explicitly stringifying
> $] (which produces a correct string) and having *that* numify (to a
> correctly-converted floating point value) for comparison.  I cultivate
> the habit of always stringifying $] to work around this, regardless of
> the threshold where the bug was fixed.  So I'd write
>
>     use if "$]" >= 5.014, warnings => "non_unicode";
This ensures that the comparisons will still work when Perl's major …

fix string comparisons with $] to use numeric comparison instead (PR#63)
